/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-03 05:37:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.PageVO;
import vo.BoardVO;
import java.util.List;
import java.text.SimpleDateFormat;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    SimpleDateFormat sdf = 
        new SimpleDateFormat("yyyy-MM-dd HH:mm");
    //2021-01-12 09:17
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("vo.BoardVO");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("vo.PageVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<BoardVO> articleList = (List<BoardVO>)request.getAttribute("articleList");
	PageVO pageVO = (PageVO)request.getAttribute("pageVO");
	int count = pageVO.getCount();
	int currentPage = pageVO.getCurrentPage();
	int startPage = pageVO.getStartPage();
	int number = pageVO.getNumber();
	int endPage = pageVO.getEndPage();
	int pageCount = pageVO.getPageCount();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>게시판</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<center><b>글목록(전체 글:");
      out.print(count);
      out.write(")</b>\r\n");
      out.write("<table width=\"700\">\r\n");
      out.write("<tr>\r\n");
      out.write("    <td align=\"right\">\r\n");
      out.write("    <a href=\"boardWriteForm.bo\">글쓰기</a>\r\n");
      out.write("    </td>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");

	if (count == 0) {

      out.write("\r\n");
      out.write("<table width=\"700\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("<tr>\r\n");
      out.write("    <td align=\"center\">\r\n");
      out.write("    게시판에 저장된 글이 없습니다.\r\n");
      out.write("    </td>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");

	} else {

      out.write("\r\n");
      out.write("<table border=\"1\" width=\"700\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\"> \r\n");
      out.write("    <tr height=\"30\"> \r\n");
      out.write("      <td align=\"center\"  width=\"50\"  >번 호</td> \r\n");
      out.write("      <td align=\"center\"  width=\"250\" >제   목</td> \r\n");
      out.write("      <td align=\"center\"  width=\"100\" >작성자</td>\r\n");
      out.write("      <td align=\"center\"  width=\"150\" >작성일</td> \r\n");
      out.write("      <td align=\"center\"  width=\"50\" >조 회</td>    \r\n");
      out.write("    </tr>\r\n");

	for (int i = 0 ; i < articleList.size() ; i++) {
          BoardVO article = (BoardVO)articleList.get(i);

      out.write("\r\n");
      out.write("   <tr height=\"30\">\r\n");
      out.write("    <td align=\"center\"  width=\"50\" > ");
      out.print(number--);
      out.write("</td>\r\n");
      out.write("    <td  width=\"250\" >\r\n");
      out.write("	");

	      int wid=0; //공백 이미지의 픽셀값
	      if(article.getRe_level()>0){
	        wid=5*(article.getRe_level());
	
      out.write("\r\n");
      out.write("	  <img src=\"board/images/level.gif\" width=\"");
      out.print(wid);
      out.write("\" height=\"16\">\r\n");
      out.write("	  <img src=\"board/images/re.gif\">\r\n");
      out.write("	");
}else{
      out.write("\r\n");
      out.write("	  <img src=\"board/images/level.gif\" width=\"");
      out.print(wid);
      out.write("\" height=\"16\">\r\n");
      out.write("	");
}
      out.write("\r\n");
      out.write("           \r\n");
      out.write("      <a href=\"boardContent.bo?num=");
      out.print(article.getNum());
      out.write("&pageNum=");
      out.print(currentPage);
      out.write("\">\r\n");
      out.write("           ");
      out.print(article.getSubject());
      out.write("</a> \r\n");
      out.write("          ");
 if(article.getReadcount()>=20){
      out.write("\r\n");
      out.write("         <img src=\"images/hot.gif\" border=\"0\"  height=\"16\">");
}
      out.write(" \r\n");
      out.write("         </td>\r\n");
      out.write("    <td align=\"center\"  width=\"100\"> \r\n");
      out.write("       <a href=\"mailto:");
      out.print(article.getEmail());
      out.write("\">\r\n");
      out.write("       ");
      out.print(article.getWriter());
      out.write("</a></td>\r\n");
      out.write("    <td align=\"center\"  width=\"150\">\r\n");
      out.write("    ");
      out.print( sdf.format(article.getReg_date()));
      out.write("</td>\r\n");
      out.write("    <td align=\"center\"  width=\"50\">");
      out.print(article.getReadcount());
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("     ");
}
      out.write("\r\n");
      out.write("</table>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");

    if (count > 0) {
        
        if (startPage > 10) { //첫번째 페이지 그룹이 아니면...  이전그룹의 startPage로 이동 
      out.write("\r\n");
      out.write("        <a href=\"boardList.bo?pageNum=");
      out.print( startPage - 10 );
      out.write("\">[이전]</a>\r\n");
      }
        for (int i = startPage ; i <= endPage ; i++) {  
      out.write("\r\n");
      out.write("        <a href=\"boardList.bo?pageNum=");
      out.print( i );
      out.write('"');
      out.write('>');
      out.write('[');
      out.print( i );
      out.write("]</a>\r\n");

        }
        if (endPage < pageCount) { //현재 페이지그룹이 마지막 페이지 그룹이 아닐때 다음 페이지그룹의 startPage로 이동 
      out.write("\r\n");
      out.write("        <a href=\"boardList.bo?pageNum=");
      out.print( startPage + 10 );
      out.write("\">[다음]</a>\r\n");

        }
    }

      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
